//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  hero: Hero;
  heroConnection: HeroConnection;
  sobre: Sobre;
  sobreConnection: SobreConnection;
  premios: Premios;
  premiosConnection: PremiosConnection;
  projetos: Projetos;
  projetosConnection: ProjetosConnection;
  galeria: Galeria;
  galeriaConnection: GaleriaConnection;
  videos: Videos;
  videosConnection: VideosConnection;
  quiz: Quiz;
  quizConnection: QuizConnection;
  livro: Livro;
  livroConnection: LivroConnection;
  footer: Footer;
  footerConnection: FooterConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeroArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeroConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
};


export type QuerySobreArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySobreConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SobreFilter>;
};


export type QueryPremiosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPremiosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PremiosFilter>;
};


export type QueryProjetosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjetosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjetosFilter>;
};


export type QueryGaleriaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGaleriaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GaleriaFilter>;
};


export type QueryVideosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryVideosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<VideosFilter>;
};


export type QueryQuizArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryQuizConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<QuizFilter>;
};


export type QueryLivroArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLivroConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LivroFilter>;
};


export type QueryFooterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFooterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FooterFilter>;
};

export type DocumentFilter = {
  hero?: InputMaybe<HeroFilter>;
  sobre?: InputMaybe<SobreFilter>;
  premios?: InputMaybe<PremiosFilter>;
  projetos?: InputMaybe<ProjetosFilter>;
  galeria?: InputMaybe<GaleriaFilter>;
  videos?: InputMaybe<VideosFilter>;
  quiz?: InputMaybe<QuizFilter>;
  livro?: InputMaybe<LivroFilter>;
  footer?: InputMaybe<FooterFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Hero | Sobre | Premios | Projetos | Galeria | Videos | Quiz | Livro | Footer | Folder;

export type Hero = Node & Document & {
  __typename?: 'Hero';
  tag?: Maybe<Scalars['String']['output']>;
  descricao?: Maybe<Scalars['String']['output']>;
  btnPrimarioTexto?: Maybe<Scalars['String']['output']>;
  btnPrimarioLink?: Maybe<Scalars['String']['output']>;
  btnSecundarioTexto?: Maybe<Scalars['String']['output']>;
  btnSecundarioLink?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HeroFilter = {
  tag?: InputMaybe<StringFilter>;
  descricao?: InputMaybe<StringFilter>;
  btnPrimarioTexto?: InputMaybe<StringFilter>;
  btnPrimarioLink?: InputMaybe<StringFilter>;
  btnSecundarioTexto?: InputMaybe<StringFilter>;
  btnSecundarioLink?: InputMaybe<StringFilter>;
};

export type HeroConnectionEdges = {
  __typename?: 'HeroConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Hero>;
};

export type HeroConnection = Connection & {
  __typename?: 'HeroConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HeroConnectionEdges>>>;
};

export type Sobre = Node & Document & {
  __typename?: 'Sobre';
  titulo?: Maybe<Scalars['String']['output']>;
  paragrafo1?: Maybe<Scalars['String']['output']>;
  paragrafo2?: Maybe<Scalars['String']['output']>;
  paragrafo3?: Maybe<Scalars['String']['output']>;
  stat1Numero?: Maybe<Scalars['String']['output']>;
  stat1Label?: Maybe<Scalars['String']['output']>;
  stat2Numero?: Maybe<Scalars['String']['output']>;
  stat2Label?: Maybe<Scalars['String']['output']>;
  stat3Numero?: Maybe<Scalars['String']['output']>;
  stat3Label?: Maybe<Scalars['String']['output']>;
  stat4Numero?: Maybe<Scalars['String']['output']>;
  stat4Label?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SobreFilter = {
  titulo?: InputMaybe<StringFilter>;
  paragrafo1?: InputMaybe<StringFilter>;
  paragrafo2?: InputMaybe<StringFilter>;
  paragrafo3?: InputMaybe<StringFilter>;
  stat1Numero?: InputMaybe<StringFilter>;
  stat1Label?: InputMaybe<StringFilter>;
  stat2Numero?: InputMaybe<StringFilter>;
  stat2Label?: InputMaybe<StringFilter>;
  stat3Numero?: InputMaybe<StringFilter>;
  stat3Label?: InputMaybe<StringFilter>;
  stat4Numero?: InputMaybe<StringFilter>;
  stat4Label?: InputMaybe<StringFilter>;
};

export type SobreConnectionEdges = {
  __typename?: 'SobreConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Sobre>;
};

export type SobreConnection = Connection & {
  __typename?: 'SobreConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SobreConnectionEdges>>>;
};

export type PremiosLista = {
  __typename?: 'PremiosLista';
  icone?: Maybe<Scalars['String']['output']>;
  titulo?: Maybe<Scalars['String']['output']>;
  descricao?: Maybe<Scalars['String']['output']>;
  ano?: Maybe<Scalars['String']['output']>;
};

export type Premios = Node & Document & {
  __typename?: 'Premios';
  lista?: Maybe<Array<Maybe<PremiosLista>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PremiosListaFilter = {
  icone?: InputMaybe<StringFilter>;
  titulo?: InputMaybe<StringFilter>;
  descricao?: InputMaybe<StringFilter>;
  ano?: InputMaybe<StringFilter>;
};

export type PremiosFilter = {
  lista?: InputMaybe<PremiosListaFilter>;
};

export type PremiosConnectionEdges = {
  __typename?: 'PremiosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Premios>;
};

export type PremiosConnection = Connection & {
  __typename?: 'PremiosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PremiosConnectionEdges>>>;
};

export type ProjetosLista = {
  __typename?: 'ProjetosLista';
  numero?: Maybe<Scalars['String']['output']>;
  titulo?: Maybe<Scalars['String']['output']>;
  descricao?: Maybe<Scalars['String']['output']>;
  badge?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
};

export type Projetos = Node & Document & {
  __typename?: 'Projetos';
  lista?: Maybe<Array<Maybe<ProjetosLista>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProjetosListaFilter = {
  numero?: InputMaybe<StringFilter>;
  titulo?: InputMaybe<StringFilter>;
  descricao?: InputMaybe<StringFilter>;
  badge?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type ProjetosFilter = {
  lista?: InputMaybe<ProjetosListaFilter>;
};

export type ProjetosConnectionEdges = {
  __typename?: 'ProjetosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Projetos>;
};

export type ProjetosConnection = Connection & {
  __typename?: 'ProjetosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjetosConnectionEdges>>>;
};

export type GaleriaItens = {
  __typename?: 'GaleriaItens';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type Galeria = Node & Document & {
  __typename?: 'Galeria';
  itens?: Maybe<Array<Maybe<GaleriaItens>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type GaleriaItensFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type GaleriaFilter = {
  itens?: InputMaybe<GaleriaItensFilter>;
};

export type GaleriaConnectionEdges = {
  __typename?: 'GaleriaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Galeria>;
};

export type GaleriaConnection = Connection & {
  __typename?: 'GaleriaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GaleriaConnectionEdges>>>;
};

export type VideosLista = {
  __typename?: 'VideosLista';
  titulo?: Maybe<Scalars['String']['output']>;
  subtitulo?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
  thumb?: Maybe<Scalars['String']['output']>;
};

export type Videos = Node & Document & {
  __typename?: 'Videos';
  lista?: Maybe<Array<Maybe<VideosLista>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type VideosListaFilter = {
  titulo?: InputMaybe<StringFilter>;
  subtitulo?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
  thumb?: InputMaybe<ImageFilter>;
};

export type VideosFilter = {
  lista?: InputMaybe<VideosListaFilter>;
};

export type VideosConnectionEdges = {
  __typename?: 'VideosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Videos>;
};

export type VideosConnection = Connection & {
  __typename?: 'VideosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<VideosConnectionEdges>>>;
};

export type QuizOpcoes = {
  __typename?: 'QuizOpcoes';
  texto?: Maybe<Scalars['String']['output']>;
};

export type Quiz = Node & Document & {
  __typename?: 'Quiz';
  titulo?: Maybe<Scalars['String']['output']>;
  descricao?: Maybe<Scalars['String']['output']>;
  opcoes?: Maybe<Array<Maybe<QuizOpcoes>>>;
  btnTexto?: Maybe<Scalars['String']['output']>;
  btnLink?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type QuizOpcoesFilter = {
  texto?: InputMaybe<StringFilter>;
};

export type QuizFilter = {
  titulo?: InputMaybe<StringFilter>;
  descricao?: InputMaybe<StringFilter>;
  opcoes?: InputMaybe<QuizOpcoesFilter>;
  btnTexto?: InputMaybe<StringFilter>;
  btnLink?: InputMaybe<StringFilter>;
};

export type QuizConnectionEdges = {
  __typename?: 'QuizConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Quiz>;
};

export type QuizConnection = Connection & {
  __typename?: 'QuizConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<QuizConnectionEdges>>>;
};

export type Livro = Node & Document & {
  __typename?: 'Livro';
  titulo?: Maybe<Scalars['String']['output']>;
  paragrafo1?: Maybe<Scalars['String']['output']>;
  paragrafo2?: Maybe<Scalars['String']['output']>;
  btn1Texto?: Maybe<Scalars['String']['output']>;
  btn1Link?: Maybe<Scalars['String']['output']>;
  btn2Texto?: Maybe<Scalars['String']['output']>;
  btn2Link?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LivroFilter = {
  titulo?: InputMaybe<StringFilter>;
  paragrafo1?: InputMaybe<StringFilter>;
  paragrafo2?: InputMaybe<StringFilter>;
  btn1Texto?: InputMaybe<StringFilter>;
  btn1Link?: InputMaybe<StringFilter>;
  btn2Texto?: InputMaybe<StringFilter>;
  btn2Link?: InputMaybe<StringFilter>;
};

export type LivroConnectionEdges = {
  __typename?: 'LivroConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Livro>;
};

export type LivroConnection = Connection & {
  __typename?: 'LivroConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LivroConnectionEdges>>>;
};

export type Footer = Node & Document & {
  __typename?: 'Footer';
  instagramLink?: Maybe<Scalars['String']['output']>;
  youtubeLink?: Maybe<Scalars['String']['output']>;
  contatoEmail?: Maybe<Scalars['String']['output']>;
  lattesLink?: Maybe<Scalars['String']['output']>;
  portfolioLink?: Maybe<Scalars['String']['output']>;
  copyright?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FooterFilter = {
  instagramLink?: InputMaybe<StringFilter>;
  youtubeLink?: InputMaybe<StringFilter>;
  contatoEmail?: InputMaybe<StringFilter>;
  lattesLink?: InputMaybe<StringFilter>;
  portfolioLink?: InputMaybe<StringFilter>;
  copyright?: InputMaybe<StringFilter>;
};

export type FooterConnectionEdges = {
  __typename?: 'FooterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Footer>;
};

export type FooterConnection = Connection & {
  __typename?: 'FooterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FooterConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHero: Hero;
  createHero: Hero;
  updateSobre: Sobre;
  createSobre: Sobre;
  updatePremios: Premios;
  createPremios: Premios;
  updateProjetos: Projetos;
  createProjetos: Projetos;
  updateGaleria: Galeria;
  createGaleria: Galeria;
  updateVideos: Videos;
  createVideos: Videos;
  updateQuiz: Quiz;
  createQuiz: Quiz;
  updateLivro: Livro;
  createLivro: Livro;
  updateFooter: Footer;
  createFooter: Footer;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationCreateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationUpdateSobreArgs = {
  relativePath: Scalars['String']['input'];
  params: SobreMutation;
};


export type MutationCreateSobreArgs = {
  relativePath: Scalars['String']['input'];
  params: SobreMutation;
};


export type MutationUpdatePremiosArgs = {
  relativePath: Scalars['String']['input'];
  params: PremiosMutation;
};


export type MutationCreatePremiosArgs = {
  relativePath: Scalars['String']['input'];
  params: PremiosMutation;
};


export type MutationUpdateProjetosArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjetosMutation;
};


export type MutationCreateProjetosArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjetosMutation;
};


export type MutationUpdateGaleriaArgs = {
  relativePath: Scalars['String']['input'];
  params: GaleriaMutation;
};


export type MutationCreateGaleriaArgs = {
  relativePath: Scalars['String']['input'];
  params: GaleriaMutation;
};


export type MutationUpdateVideosArgs = {
  relativePath: Scalars['String']['input'];
  params: VideosMutation;
};


export type MutationCreateVideosArgs = {
  relativePath: Scalars['String']['input'];
  params: VideosMutation;
};


export type MutationUpdateQuizArgs = {
  relativePath: Scalars['String']['input'];
  params: QuizMutation;
};


export type MutationCreateQuizArgs = {
  relativePath: Scalars['String']['input'];
  params: QuizMutation;
};


export type MutationUpdateLivroArgs = {
  relativePath: Scalars['String']['input'];
  params: LivroMutation;
};


export type MutationCreateLivroArgs = {
  relativePath: Scalars['String']['input'];
  params: LivroMutation;
};


export type MutationUpdateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};


export type MutationCreateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};

export type DocumentUpdateMutation = {
  hero?: InputMaybe<HeroMutation>;
  sobre?: InputMaybe<SobreMutation>;
  premios?: InputMaybe<PremiosMutation>;
  projetos?: InputMaybe<ProjetosMutation>;
  galeria?: InputMaybe<GaleriaMutation>;
  videos?: InputMaybe<VideosMutation>;
  quiz?: InputMaybe<QuizMutation>;
  livro?: InputMaybe<LivroMutation>;
  footer?: InputMaybe<FooterMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  hero?: InputMaybe<HeroMutation>;
  sobre?: InputMaybe<SobreMutation>;
  premios?: InputMaybe<PremiosMutation>;
  projetos?: InputMaybe<ProjetosMutation>;
  galeria?: InputMaybe<GaleriaMutation>;
  videos?: InputMaybe<VideosMutation>;
  quiz?: InputMaybe<QuizMutation>;
  livro?: InputMaybe<LivroMutation>;
  footer?: InputMaybe<FooterMutation>;
};

export type HeroMutation = {
  tag?: InputMaybe<Scalars['String']['input']>;
  descricao?: InputMaybe<Scalars['String']['input']>;
  btnPrimarioTexto?: InputMaybe<Scalars['String']['input']>;
  btnPrimarioLink?: InputMaybe<Scalars['String']['input']>;
  btnSecundarioTexto?: InputMaybe<Scalars['String']['input']>;
  btnSecundarioLink?: InputMaybe<Scalars['String']['input']>;
};

export type SobreMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  paragrafo1?: InputMaybe<Scalars['String']['input']>;
  paragrafo2?: InputMaybe<Scalars['String']['input']>;
  paragrafo3?: InputMaybe<Scalars['String']['input']>;
  stat1Numero?: InputMaybe<Scalars['String']['input']>;
  stat1Label?: InputMaybe<Scalars['String']['input']>;
  stat2Numero?: InputMaybe<Scalars['String']['input']>;
  stat2Label?: InputMaybe<Scalars['String']['input']>;
  stat3Numero?: InputMaybe<Scalars['String']['input']>;
  stat3Label?: InputMaybe<Scalars['String']['input']>;
  stat4Numero?: InputMaybe<Scalars['String']['input']>;
  stat4Label?: InputMaybe<Scalars['String']['input']>;
};

export type PremiosListaMutation = {
  icone?: InputMaybe<Scalars['String']['input']>;
  titulo?: InputMaybe<Scalars['String']['input']>;
  descricao?: InputMaybe<Scalars['String']['input']>;
  ano?: InputMaybe<Scalars['String']['input']>;
};

export type PremiosMutation = {
  lista?: InputMaybe<Array<InputMaybe<PremiosListaMutation>>>;
};

export type ProjetosListaMutation = {
  numero?: InputMaybe<Scalars['String']['input']>;
  titulo?: InputMaybe<Scalars['String']['input']>;
  descricao?: InputMaybe<Scalars['String']['input']>;
  badge?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
};

export type ProjetosMutation = {
  lista?: InputMaybe<Array<InputMaybe<ProjetosListaMutation>>>;
};

export type GaleriaItensMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type GaleriaMutation = {
  itens?: InputMaybe<Array<InputMaybe<GaleriaItensMutation>>>;
};

export type VideosListaMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  subtitulo?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
  thumb?: InputMaybe<Scalars['String']['input']>;
};

export type VideosMutation = {
  lista?: InputMaybe<Array<InputMaybe<VideosListaMutation>>>;
};

export type QuizOpcoesMutation = {
  texto?: InputMaybe<Scalars['String']['input']>;
};

export type QuizMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  descricao?: InputMaybe<Scalars['String']['input']>;
  opcoes?: InputMaybe<Array<InputMaybe<QuizOpcoesMutation>>>;
  btnTexto?: InputMaybe<Scalars['String']['input']>;
  btnLink?: InputMaybe<Scalars['String']['input']>;
};

export type LivroMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  paragrafo1?: InputMaybe<Scalars['String']['input']>;
  paragrafo2?: InputMaybe<Scalars['String']['input']>;
  btn1Texto?: InputMaybe<Scalars['String']['input']>;
  btn1Link?: InputMaybe<Scalars['String']['input']>;
  btn2Texto?: InputMaybe<Scalars['String']['input']>;
  btn2Link?: InputMaybe<Scalars['String']['input']>;
};

export type FooterMutation = {
  instagramLink?: InputMaybe<Scalars['String']['input']>;
  youtubeLink?: InputMaybe<Scalars['String']['input']>;
  contatoEmail?: InputMaybe<Scalars['String']['input']>;
  lattesLink?: InputMaybe<Scalars['String']['input']>;
  portfolioLink?: InputMaybe<Scalars['String']['input']>;
  copyright?: InputMaybe<Scalars['String']['input']>;
};

export type HeroPartsFragment = { __typename: 'Hero', tag?: string | null, descricao?: string | null, btnPrimarioTexto?: string | null, btnPrimarioLink?: string | null, btnSecundarioTexto?: string | null, btnSecundarioLink?: string | null };

export type SobrePartsFragment = { __typename: 'Sobre', titulo?: string | null, paragrafo1?: string | null, paragrafo2?: string | null, paragrafo3?: string | null, stat1Numero?: string | null, stat1Label?: string | null, stat2Numero?: string | null, stat2Label?: string | null, stat3Numero?: string | null, stat3Label?: string | null, stat4Numero?: string | null, stat4Label?: string | null };

export type PremiosPartsFragment = { __typename: 'Premios', lista?: Array<{ __typename: 'PremiosLista', icone?: string | null, titulo?: string | null, descricao?: string | null, ano?: string | null } | null> | null };

export type ProjetosPartsFragment = { __typename: 'Projetos', lista?: Array<{ __typename: 'ProjetosLista', numero?: string | null, titulo?: string | null, descricao?: string | null, badge?: string | null, link?: string | null } | null> | null };

export type GaleriaPartsFragment = { __typename: 'Galeria', itens?: Array<{ __typename: 'GaleriaItens', src?: string | null, alt?: string | null } | null> | null };

export type VideosPartsFragment = { __typename: 'Videos', lista?: Array<{ __typename: 'VideosLista', titulo?: string | null, subtitulo?: string | null, link?: string | null, thumb?: string | null } | null> | null };

export type QuizPartsFragment = { __typename: 'Quiz', titulo?: string | null, descricao?: string | null, btnTexto?: string | null, btnLink?: string | null, opcoes?: Array<{ __typename: 'QuizOpcoes', texto?: string | null } | null> | null };

export type LivroPartsFragment = { __typename: 'Livro', titulo?: string | null, paragrafo1?: string | null, paragrafo2?: string | null, btn1Texto?: string | null, btn1Link?: string | null, btn2Texto?: string | null, btn2Link?: string | null };

export type FooterPartsFragment = { __typename: 'Footer', instagramLink?: string | null, youtubeLink?: string | null, contatoEmail?: string | null, lattesLink?: string | null, portfolioLink?: string | null, copyright?: string | null };

export type HeroQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HeroQuery = { __typename?: 'Query', hero: { __typename: 'Hero', id: string, tag?: string | null, descricao?: string | null, btnPrimarioTexto?: string | null, btnPrimarioLink?: string | null, btnSecundarioTexto?: string | null, btnSecundarioLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HeroConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
}>;


export type HeroConnectionQuery = { __typename?: 'Query', heroConnection: { __typename?: 'HeroConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HeroConnectionEdges', cursor: string, node?: { __typename: 'Hero', id: string, tag?: string | null, descricao?: string | null, btnPrimarioTexto?: string | null, btnPrimarioLink?: string | null, btnSecundarioTexto?: string | null, btnSecundarioLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SobreQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SobreQuery = { __typename?: 'Query', sobre: { __typename: 'Sobre', id: string, titulo?: string | null, paragrafo1?: string | null, paragrafo2?: string | null, paragrafo3?: string | null, stat1Numero?: string | null, stat1Label?: string | null, stat2Numero?: string | null, stat2Label?: string | null, stat3Numero?: string | null, stat3Label?: string | null, stat4Numero?: string | null, stat4Label?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SobreConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SobreFilter>;
}>;


export type SobreConnectionQuery = { __typename?: 'Query', sobreConnection: { __typename?: 'SobreConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SobreConnectionEdges', cursor: string, node?: { __typename: 'Sobre', id: string, titulo?: string | null, paragrafo1?: string | null, paragrafo2?: string | null, paragrafo3?: string | null, stat1Numero?: string | null, stat1Label?: string | null, stat2Numero?: string | null, stat2Label?: string | null, stat3Numero?: string | null, stat3Label?: string | null, stat4Numero?: string | null, stat4Label?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PremiosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PremiosQuery = { __typename?: 'Query', premios: { __typename: 'Premios', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, lista?: Array<{ __typename: 'PremiosLista', icone?: string | null, titulo?: string | null, descricao?: string | null, ano?: string | null } | null> | null } };

export type PremiosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PremiosFilter>;
}>;


export type PremiosConnectionQuery = { __typename?: 'Query', premiosConnection: { __typename?: 'PremiosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PremiosConnectionEdges', cursor: string, node?: { __typename: 'Premios', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, lista?: Array<{ __typename: 'PremiosLista', icone?: string | null, titulo?: string | null, descricao?: string | null, ano?: string | null } | null> | null } | null } | null> | null } };

export type ProjetosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjetosQuery = { __typename?: 'Query', projetos: { __typename: 'Projetos', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, lista?: Array<{ __typename: 'ProjetosLista', numero?: string | null, titulo?: string | null, descricao?: string | null, badge?: string | null, link?: string | null } | null> | null } };

export type ProjetosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjetosFilter>;
}>;


export type ProjetosConnectionQuery = { __typename?: 'Query', projetosConnection: { __typename?: 'ProjetosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjetosConnectionEdges', cursor: string, node?: { __typename: 'Projetos', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, lista?: Array<{ __typename: 'ProjetosLista', numero?: string | null, titulo?: string | null, descricao?: string | null, badge?: string | null, link?: string | null } | null> | null } | null } | null> | null } };

export type GaleriaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GaleriaQuery = { __typename?: 'Query', galeria: { __typename: 'Galeria', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, itens?: Array<{ __typename: 'GaleriaItens', src?: string | null, alt?: string | null } | null> | null } };

export type GaleriaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GaleriaFilter>;
}>;


export type GaleriaConnectionQuery = { __typename?: 'Query', galeriaConnection: { __typename?: 'GaleriaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GaleriaConnectionEdges', cursor: string, node?: { __typename: 'Galeria', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, itens?: Array<{ __typename: 'GaleriaItens', src?: string | null, alt?: string | null } | null> | null } | null } | null> | null } };

export type VideosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type VideosQuery = { __typename?: 'Query', videos: { __typename: 'Videos', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, lista?: Array<{ __typename: 'VideosLista', titulo?: string | null, subtitulo?: string | null, link?: string | null, thumb?: string | null } | null> | null } };

export type VideosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<VideosFilter>;
}>;


export type VideosConnectionQuery = { __typename?: 'Query', videosConnection: { __typename?: 'VideosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'VideosConnectionEdges', cursor: string, node?: { __typename: 'Videos', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, lista?: Array<{ __typename: 'VideosLista', titulo?: string | null, subtitulo?: string | null, link?: string | null, thumb?: string | null } | null> | null } | null } | null> | null } };

export type QuizQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type QuizQuery = { __typename?: 'Query', quiz: { __typename: 'Quiz', id: string, titulo?: string | null, descricao?: string | null, btnTexto?: string | null, btnLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, opcoes?: Array<{ __typename: 'QuizOpcoes', texto?: string | null } | null> | null } };

export type QuizConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<QuizFilter>;
}>;


export type QuizConnectionQuery = { __typename?: 'Query', quizConnection: { __typename?: 'QuizConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'QuizConnectionEdges', cursor: string, node?: { __typename: 'Quiz', id: string, titulo?: string | null, descricao?: string | null, btnTexto?: string | null, btnLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, opcoes?: Array<{ __typename: 'QuizOpcoes', texto?: string | null } | null> | null } | null } | null> | null } };

export type LivroQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LivroQuery = { __typename?: 'Query', livro: { __typename: 'Livro', id: string, titulo?: string | null, paragrafo1?: string | null, paragrafo2?: string | null, btn1Texto?: string | null, btn1Link?: string | null, btn2Texto?: string | null, btn2Link?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type LivroConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LivroFilter>;
}>;


export type LivroConnectionQuery = { __typename?: 'Query', livroConnection: { __typename?: 'LivroConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LivroConnectionEdges', cursor: string, node?: { __typename: 'Livro', id: string, titulo?: string | null, paragrafo1?: string | null, paragrafo2?: string | null, btn1Texto?: string | null, btn1Link?: string | null, btn2Texto?: string | null, btn2Link?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FooterQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FooterQuery = { __typename?: 'Query', footer: { __typename: 'Footer', id: string, instagramLink?: string | null, youtubeLink?: string | null, contatoEmail?: string | null, lattesLink?: string | null, portfolioLink?: string | null, copyright?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FooterConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FooterFilter>;
}>;


export type FooterConnectionQuery = { __typename?: 'Query', footerConnection: { __typename?: 'FooterConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FooterConnectionEdges', cursor: string, node?: { __typename: 'Footer', id: string, instagramLink?: string | null, youtubeLink?: string | null, contatoEmail?: string | null, lattesLink?: string | null, portfolioLink?: string | null, copyright?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HeroPartsFragmentDoc = gql`
    fragment HeroParts on Hero {
  __typename
  tag
  descricao
  btnPrimarioTexto
  btnPrimarioLink
  btnSecundarioTexto
  btnSecundarioLink
}
    `;
export const SobrePartsFragmentDoc = gql`
    fragment SobreParts on Sobre {
  __typename
  titulo
  paragrafo1
  paragrafo2
  paragrafo3
  stat1Numero
  stat1Label
  stat2Numero
  stat2Label
  stat3Numero
  stat3Label
  stat4Numero
  stat4Label
}
    `;
export const PremiosPartsFragmentDoc = gql`
    fragment PremiosParts on Premios {
  __typename
  lista {
    __typename
    icone
    titulo
    descricao
    ano
  }
}
    `;
export const ProjetosPartsFragmentDoc = gql`
    fragment ProjetosParts on Projetos {
  __typename
  lista {
    __typename
    numero
    titulo
    descricao
    badge
    link
  }
}
    `;
export const GaleriaPartsFragmentDoc = gql`
    fragment GaleriaParts on Galeria {
  __typename
  itens {
    __typename
    src
    alt
  }
}
    `;
export const VideosPartsFragmentDoc = gql`
    fragment VideosParts on Videos {
  __typename
  lista {
    __typename
    titulo
    subtitulo
    link
    thumb
  }
}
    `;
export const QuizPartsFragmentDoc = gql`
    fragment QuizParts on Quiz {
  __typename
  titulo
  descricao
  opcoes {
    __typename
    texto
  }
  btnTexto
  btnLink
}
    `;
export const LivroPartsFragmentDoc = gql`
    fragment LivroParts on Livro {
  __typename
  titulo
  paragrafo1
  paragrafo2
  btn1Texto
  btn1Link
  btn2Texto
  btn2Link
}
    `;
export const FooterPartsFragmentDoc = gql`
    fragment FooterParts on Footer {
  __typename
  instagramLink
  youtubeLink
  contatoEmail
  lattesLink
  portfolioLink
  copyright
}
    `;
export const HeroDocument = gql`
    query hero($relativePath: String!) {
  hero(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HeroParts
  }
}
    ${HeroPartsFragmentDoc}`;
export const HeroConnectionDocument = gql`
    query heroConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HeroFilter) {
  heroConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HeroParts
      }
    }
  }
}
    ${HeroPartsFragmentDoc}`;
export const SobreDocument = gql`
    query sobre($relativePath: String!) {
  sobre(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SobreParts
  }
}
    ${SobrePartsFragmentDoc}`;
export const SobreConnectionDocument = gql`
    query sobreConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SobreFilter) {
  sobreConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SobreParts
      }
    }
  }
}
    ${SobrePartsFragmentDoc}`;
export const PremiosDocument = gql`
    query premios($relativePath: String!) {
  premios(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PremiosParts
  }
}
    ${PremiosPartsFragmentDoc}`;
export const PremiosConnectionDocument = gql`
    query premiosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PremiosFilter) {
  premiosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PremiosParts
      }
    }
  }
}
    ${PremiosPartsFragmentDoc}`;
export const ProjetosDocument = gql`
    query projetos($relativePath: String!) {
  projetos(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjetosParts
  }
}
    ${ProjetosPartsFragmentDoc}`;
export const ProjetosConnectionDocument = gql`
    query projetosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjetosFilter) {
  projetosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjetosParts
      }
    }
  }
}
    ${ProjetosPartsFragmentDoc}`;
export const GaleriaDocument = gql`
    query galeria($relativePath: String!) {
  galeria(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GaleriaParts
  }
}
    ${GaleriaPartsFragmentDoc}`;
export const GaleriaConnectionDocument = gql`
    query galeriaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GaleriaFilter) {
  galeriaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GaleriaParts
      }
    }
  }
}
    ${GaleriaPartsFragmentDoc}`;
export const VideosDocument = gql`
    query videos($relativePath: String!) {
  videos(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...VideosParts
  }
}
    ${VideosPartsFragmentDoc}`;
export const VideosConnectionDocument = gql`
    query videosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: VideosFilter) {
  videosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...VideosParts
      }
    }
  }
}
    ${VideosPartsFragmentDoc}`;
export const QuizDocument = gql`
    query quiz($relativePath: String!) {
  quiz(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...QuizParts
  }
}
    ${QuizPartsFragmentDoc}`;
export const QuizConnectionDocument = gql`
    query quizConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: QuizFilter) {
  quizConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...QuizParts
      }
    }
  }
}
    ${QuizPartsFragmentDoc}`;
export const LivroDocument = gql`
    query livro($relativePath: String!) {
  livro(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LivroParts
  }
}
    ${LivroPartsFragmentDoc}`;
export const LivroConnectionDocument = gql`
    query livroConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LivroFilter) {
  livroConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LivroParts
      }
    }
  }
}
    ${LivroPartsFragmentDoc}`;
export const FooterDocument = gql`
    query footer($relativePath: String!) {
  footer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FooterParts
  }
}
    ${FooterPartsFragmentDoc}`;
export const FooterConnectionDocument = gql`
    query footerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FooterFilter) {
  footerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FooterParts
      }
    }
  }
}
    ${FooterPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      hero(variables: HeroQueryVariables, options?: C): Promise<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}> {
        return requester<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}, HeroQueryVariables>(HeroDocument, variables, options);
      },
    heroConnection(variables?: HeroConnectionQueryVariables, options?: C): Promise<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}> {
        return requester<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}, HeroConnectionQueryVariables>(HeroConnectionDocument, variables, options);
      },
    sobre(variables: SobreQueryVariables, options?: C): Promise<{data: SobreQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SobreQueryVariables, query: string}> {
        return requester<{data: SobreQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SobreQueryVariables, query: string}, SobreQueryVariables>(SobreDocument, variables, options);
      },
    sobreConnection(variables?: SobreConnectionQueryVariables, options?: C): Promise<{data: SobreConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SobreConnectionQueryVariables, query: string}> {
        return requester<{data: SobreConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SobreConnectionQueryVariables, query: string}, SobreConnectionQueryVariables>(SobreConnectionDocument, variables, options);
      },
    premios(variables: PremiosQueryVariables, options?: C): Promise<{data: PremiosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PremiosQueryVariables, query: string}> {
        return requester<{data: PremiosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PremiosQueryVariables, query: string}, PremiosQueryVariables>(PremiosDocument, variables, options);
      },
    premiosConnection(variables?: PremiosConnectionQueryVariables, options?: C): Promise<{data: PremiosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PremiosConnectionQueryVariables, query: string}> {
        return requester<{data: PremiosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PremiosConnectionQueryVariables, query: string}, PremiosConnectionQueryVariables>(PremiosConnectionDocument, variables, options);
      },
    projetos(variables: ProjetosQueryVariables, options?: C): Promise<{data: ProjetosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjetosQueryVariables, query: string}> {
        return requester<{data: ProjetosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjetosQueryVariables, query: string}, ProjetosQueryVariables>(ProjetosDocument, variables, options);
      },
    projetosConnection(variables?: ProjetosConnectionQueryVariables, options?: C): Promise<{data: ProjetosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjetosConnectionQueryVariables, query: string}> {
        return requester<{data: ProjetosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjetosConnectionQueryVariables, query: string}, ProjetosConnectionQueryVariables>(ProjetosConnectionDocument, variables, options);
      },
    galeria(variables: GaleriaQueryVariables, options?: C): Promise<{data: GaleriaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GaleriaQueryVariables, query: string}> {
        return requester<{data: GaleriaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GaleriaQueryVariables, query: string}, GaleriaQueryVariables>(GaleriaDocument, variables, options);
      },
    galeriaConnection(variables?: GaleriaConnectionQueryVariables, options?: C): Promise<{data: GaleriaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GaleriaConnectionQueryVariables, query: string}> {
        return requester<{data: GaleriaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GaleriaConnectionQueryVariables, query: string}, GaleriaConnectionQueryVariables>(GaleriaConnectionDocument, variables, options);
      },
    videos(variables: VideosQueryVariables, options?: C): Promise<{data: VideosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideosQueryVariables, query: string}> {
        return requester<{data: VideosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideosQueryVariables, query: string}, VideosQueryVariables>(VideosDocument, variables, options);
      },
    videosConnection(variables?: VideosConnectionQueryVariables, options?: C): Promise<{data: VideosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideosConnectionQueryVariables, query: string}> {
        return requester<{data: VideosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideosConnectionQueryVariables, query: string}, VideosConnectionQueryVariables>(VideosConnectionDocument, variables, options);
      },
    quiz(variables: QuizQueryVariables, options?: C): Promise<{data: QuizQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuizQueryVariables, query: string}> {
        return requester<{data: QuizQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuizQueryVariables, query: string}, QuizQueryVariables>(QuizDocument, variables, options);
      },
    quizConnection(variables?: QuizConnectionQueryVariables, options?: C): Promise<{data: QuizConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuizConnectionQueryVariables, query: string}> {
        return requester<{data: QuizConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuizConnectionQueryVariables, query: string}, QuizConnectionQueryVariables>(QuizConnectionDocument, variables, options);
      },
    livro(variables: LivroQueryVariables, options?: C): Promise<{data: LivroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LivroQueryVariables, query: string}> {
        return requester<{data: LivroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LivroQueryVariables, query: string}, LivroQueryVariables>(LivroDocument, variables, options);
      },
    livroConnection(variables?: LivroConnectionQueryVariables, options?: C): Promise<{data: LivroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LivroConnectionQueryVariables, query: string}> {
        return requester<{data: LivroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LivroConnectionQueryVariables, query: string}, LivroConnectionQueryVariables>(LivroConnectionDocument, variables, options);
      },
    footer(variables: FooterQueryVariables, options?: C): Promise<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}> {
        return requester<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}, FooterQueryVariables>(FooterDocument, variables, options);
      },
    footerConnection(variables?: FooterConnectionQueryVariables, options?: C): Promise<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}> {
        return requester<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}, FooterConnectionQueryVariables>(FooterConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  